from __future__ import annotations

PAYMENTS_API_MAX_TIMEOUT_SECONDS = 30.0
PAYMENTS_API_MAX_CONNECT_TIMEOUT_SECONDS = 10.0
PAYMENTS_API_MAX_READ_TIMEOUT_SECONDS = 30.0
PAYMENTS_API_MAX_WRITE_TIMEOUT_SECONDS = 30.0
PAYMENTS_API_MAX_POOL_TIMEOUT_SECONDS = 10.0
PAYMENTS_API_MAX_RETRIES = 3
PAYMENTS_API_MAX_RETRY_BACKOFF_SECONDS = 5.0
